spring:
    application:
        name: ${spring.application.name}
    config:
        name: ${spring.application.name}
        import: ${spring.config.import}
    profiles:
        active:
            - ${spring.profiles.active}